In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Understanding The Data

### Loading The Datasets

In [2]:
df_fulfill=pd.read_csv('Fulfillment.csv')
df_fulfill.sample(10)

,Product Name,Warehouse Order Fulfillment (days)
36,Clicgear Rovic Cooler Bag,6.5
3,Nike Men's Free 5.0+ Running Shoe,9.4
87,Garmin Approach S3 Golf GPS Watch,4.5
105,Pelican Maverick 100X Kayak,2.3
67,LIJA Women's Mid-Length Panel Golf Shorts,8.0
18,Glove It Women's Mod Oval 3-Zip Carry All Gol,3.3
52,Under Armour Kids' Mercenary Slide,4.2
40,Titleist Pro V1 High Numbers Personalized Gol,3.3
72,Nike Men's Free TR 5.0 TB Training Shoe,3.3
27,Hirzl Women's Soffft Flex Golf Glove,7.6

In [3]:
df_inv=pd.read_csv('Inventory.csv')
df_inv.sample(10)

,Product Name,Year Month,Warehouse Inventory,Inventory Cost Per Unit
152,TYR Boys' Team Digi Jammer,201711,0,1.29350
2242,Perfect Fitness Perfect Rip Deck,201605,884,2.13911
3477,Web Camera,201507,0,2.16093
3650,GoPro HERO3+ Black Edition Camera,201506,0,0.12421
1154,Mio ALPHA Heart Rate Monitor/Sport Watch,201703,0,1.15999
1509,TaylorMade 2017 Purelite Stand Bag,201612,0,0.54514
2686,Merrell Women's Siren Mid Waterproof Hiking B,201602,0,2.34452
1815,Under Armour Men's Tech II T-Shirt,201609,0,0.20703
872,Team Golf New England Patriots Putter Grip,201705,0,1.74026
3054,Polar Loop Activity Tracker,201511,0,1.92618

In [23]:
df_order=pd.read_csv('Orders_and_shipments.csv', encoding='latin1')
df_order.sample(10)
df_order.sample(10)

,Order ID,Order Item ID,Order YearMonth,Order Year,Order Month,Order Day,Order Time,Order Quantity,Product Department,Product Category,...,Customer Country,Warehouse Country,Shipment Year,Shipment Month,Shipment Day,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit
17230,29373,73486,201603,2016,3,4,18:19,1,Fan Shop,Fishing,...,Australia,USA,2016,3,8,Second Class,2,400,0.02,200
30132,55528,138878,201703,2017,3,21,13:34,1,Fan Shop,Water Sports,...,Mexico,Puerto Rico,2017,3,25,Second Class,2,200,0.04,100
18163,63086,157728,201707,2017,7,9,21:29,1,Fan Shop,Camping & Hiking,...,Denmark,USA,2017,7,11,First Class,1,300,0.02,150
24016,31226,78038,201603,2016,3,31,19:30,5,Golf,Shop By Sport,...,New zealand,Puerto Rico,2016,4,2,First Class,1,200,0.13,97
1437,25215,63196,201601,2016,1,4,01:35,2,Apparel,Cleats,...,China,Puerto Rico,2016,1,10,Standard Class,4,120,0.18,147
3864,61665,154168,201706,2017,6,21,11:21,1,Fan Shop,Water Sports,...,United Kingdom,USA,2017,6,26,Standard Class,4,200,0.02,100
13701,29888,74782,201603,2016,3,12,06:44,2,Apparel,Cleats,...,Indonesia,USA,2016,3,16,Standard Class,4,120,0.17,147
27134,37561,93753,201510,2015,10,6,12:13,5,Fan Shop,Indoor/Outdoor Games,...,USA,Puerto Rico,2015,10,7,Second Class,2,250,0.09,125
25095,6338,15861,201504,2015,4,3,12:08,1,Apparel,Men's Footwear,...,Mexico,Puerto Rico,2015,4,7,Standard Class,4,130,0.13,65
12238,63506,158754,201511,2015,11,17,18:07,3,Footwear,Cardio Equipment,...,United Kingdom,USA,2015,11,22,Same Day,3,300,0.13,245

In [24]:
df_fulfill.isna().sum()

Product Name                            0
 Warehouse Order Fulfillment (days)     0
dtype: int64

In [25]:
df_fulfill.shape

(118, 2)

In [26]:
df_inv['Year']=df_inv[' Year Month '].apply(lambda x:int(str(x)[:4]))
df_inv['Month']=df_inv[' Year Month '].apply(lambda x:int(str(x)[4:]))
df_inv.drop(columns=' Year Month ',inplace=True)
df_inv

,Product Name,Warehouse Inventory,Inventory Cost Per Unit,Year,Month
0,Perfect Fitness Perfect Rip Deck,0,0.69517,2017,12
1,Nike Men's Dri-FIT Victory Golf Polo,2,1.29291,2017,12
2,O'Brien Men's Neoprene Life Vest,0,0.56531,2017,12
3,Nike Men's Free 5.0+ Running Shoe,1,1.26321,2017,12
4,Under Armour Girls' Toddler Spine Surge Runni,0,1.47648,2017,12
...,...,...,...,...,...
4195,TaylorMade 2017 Purelite Stand Bag,0,1.44662,2015,1
4196,Ogio Race Golf Shoes,0,0.10310,2015,1
4197,GolfBuddy VT3 GPS Watch,0,1.77747,2015,1
4198,Titleist Small Wheeled Travel Cover,0,0.15244,2015,1
4199,Polar Loop Activity Tracker,1,0.88259,2015,1